### ISSUE TITLE
An Admin should not be able to delete own account

### ISSUE THREAD

**Issue by pwannenmacher** [Frachtwerk/essencium-backend#106]
# Bug-Report

Currently a user having the Role ADMIN can delete itself via API. In case of `admin@frachtwerk.de` (or any other admin-user configured via ENV-Variables) the user will be recreated on application restart with a default password.

## Steps to reproduce

Call `DELETE ../v1/users/{{own_id}}` and see what happens....

## Expected behavior

An Admin should not be able to delete own account

## Additional information

**Comment by hoelger-frachtwerk** [comment]
Maybe stupid questions, I just try to understand things on the long run.
Would this mean that an admin can never be deleted? I guess not. So then the workflow would be that the admin makes himself (1) standard user and then (2) deletes himself. The question I now have: Who ensures that there is at least one admin in the system? (I simply assume that this is a requirement, to have admins :P)

**Comment by pwannenmacher** [comment]
That is precisely the problem. If the last remaining admin deletes himself, there is no longer an admin. A solution is being considered that prevents certain changes to your own user. For example, an admin should not be able to remove the basic admin role from his own roles or delete himself.

**Comment by JelmenGuhlke** [comment]
@pwannenmacher @hoelger-frachtwerk during the rebase of https://github.com/Frachtwerk/essencium-backend/issues/334 on-top of main, due to some merge conflicts I needed to have a look into the changes made with this ticket.
As far I understand this ticket correctly, the ultimate final target is that *at every given time at least one user with an admin role is in the system*. The current implementation has the per-assumption, that this condition only can be interrupted by an human action (REST call), which leads to a close-knit between the `AbstractUserService` and the Security / Authentication implementation of Spring.
From my point of view, the current logged in user is totally unrelated to ensure the above condition. At the end, we "only" need to check, if after the changes which are planned to made (like deleting a user -> role connection or a user at all) still a user with an admin role is in the system. Regardless of any logged in user or the origin of the change (REST, CRON, event listener, ...)
With this given, the `abortWhenRemovingAdminRole` function can be simplified, e.g. like this pseudocode implementation:

```java
Set<Right> adminRights = adminRightsService.getAdminRights();

 boolean remaining = userRepository.findWhereRoleNameIsInAndUserIdIsNot(adminRights, userToUpdateId);

if (!remaining) {
  throw new NotAllowedException(
          "You cannot remove the role 'ADMIN'. That is to ensure there's at least one ADMIN remaining.");
}
```

Besides this a lot of code can be removed, which is not needed anymore. Like:
- the `remainAdmin` calculation in `AbstractUserService`
- the `DefaultRoleInitializer` has not to be injected in the `AbstractUserService`
- from all unit tests the `SecurityContextHolder` related code

> regardless of any change written above, the insecure and incorrect `boolean doModifyMyself = executingUser.getId() == id` needs to be replaced with an `.equals()`, since the ID can be a `UUID` object (in `abortWhenRemovingAdminRole`)

What are your thoughts on this?

**Comment by hoelger-frachtwerk** [comment]
Nice and elegant way of thinking!

Only thing I see, is that the "remaining" formula will become a little more complex, because you have `existsWhereRoleNameIsInAndUserIdIsNot` and have to add `+1` in case the `userToUpdateId` has the Admin role _after_ the changes. But still this would be independent of the calling user then.

One disadvantage I see: it is quite inefficient if you crawl the complete database with 10.000 users, to look if there are 1, 2, 3 or 10 Admins remaining. And this for any change you do on the users, not even related to roles and rights. Or is the computation effort reasonable due to the `exists` (which I read as an "early abort when found")

@pwannenmacher what do you think? Should we go forward and implement this, or are there other things we don't see?

**Comment by JelmenGuhlke** [comment]
The current implementation is in my opinion too narrow - and only half way correct. For example it is not possible to remove an `ADMIN` role from myself (over the PATCH `/v1/users/`, not over the PATCH `/v1/me/` since only `final var permittedFields = Set.of("firstName", "lastName", "phone", "mobile", "locale");` fields are permitted), although there is still at least one user with admin role in the system. In addition to that - as written above - , the current check would allow a "remove of the last admin", if the service is called from a not user initialized session, like a CRON job. From my point of view these two points are enough reason to re-implement the logic: away from a "who is logged-in view" to a "what is the state, after the update view".
Regarding the costs for the `exists` query - if have tested it locally with 100k users and 50k admins; the answers is still ready in <100ms. I think the more interesting part is to check, when the query needs to be fired: for example if the update roles contains an ADMIN role, the query is unnecessary.
