### ISSUE TITLE
Enforce basic password policy for new users

### ISSUE THREAD

**Issue by pwannenmacher** [Frachtwerk/essencium-backend#99]
# Feature Request

To prevent users from using weak passwords essencium should enforce a password policy.

## Use-Case

see above

## Implementation proposals

* https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls
* Potentially use http://www.passay.org/
* Write custom validation annotation
  * Implement a `PasswordPolicyValidator`, i.e. something implementing `ConstraintValidator`
  * Create annotation class, annotated with `@Constraint(validatedBy = PasswordPolicyValidator.class)`
  * Annotate password field of `UserDto`

## Additional Information

**Comment by hoelger-frachtwerk** [comment]
After playing around with this [tester](https://lowe.github.io/tryzxcvbn/)

The only improving comments I can get from it are:
- Add another word or two. Uncommon words are better.
- Capitalization doesn't help very much 
- Predictable substitutions like '@' instead of 'a' don't help very much 
- (They don't feed back some rules like "you miss one uppercase letter")

I don't find this too much enlightening, and in case we want to display this to the user, I propose to implement the `zxcvbn` library in the [frontend code](https://github.com/dropbox/zxcvbn). @qhantom 

German passwords rank a little higher because they cannot be found in the dict of `zxcvbn`.

From my short experience: Even if you use some words lowercase after each other (`dubisthallo`) the ranks don't really change compared to uppercase and special chars. 

Very rougly:
With 8 chars you score 2/4
With 10 chars you score 3/4
With 12 chars you score 4/4

For development I suggest to raise the quality gate to `3` (now `adminAdminAdmin` is ok). For some production scenario, it would be good to raise the quality gate to `4`.

**Comment by hoelger-frachtwerk** [comment]
Read this article to see how paradigm of "what is a strong password" has shifted - or is very much opinion based.

https://dropbox.tech/security/zxcvbn-realistic-password-strength-estimation

**Comment by qhantom** [comment]
> After playing around with this [tester](https://lowe.github.io/tryzxcvbn/)
> 
> The only improving comments I can get from it are:
> 
> * Add another word or two. Uncommon words are better.
> * Capitalization doesn't help very much
> * Predictable substitutions like '@' instead of 'a' don't help very much
> * (They don't feed back some rules like "you miss one uppercase letter")
> 
> I don't find this too much enlightening, and in case we want to display this to the user, I propose to implement the `zxcvbn` library in the [frontend code](https://github.com/dropbox/zxcvbn). @qhantom
> 
> German passwords rank a little higher because they cannot be found in the dict of `zxcvbn`.
> 
> From my short experience: Even if you use some words lowercase after each other (`dubisthallo`) the ranks don't really change compared to uppercase and special chars.
> 
> Very rougly: With 8 chars you score 2/4 With 10 chars you score 3/4 With 12 chars you score 4/4
> 
> For development I suggest to raise the quality gate to `3` (now `adminAdminAdmin` is ok). For some production scenario, it would be good to raise the quality gate to `4`.

Thanks! Your quoted library could be used, we had it installed in the past but it was pretty large and increased the bundle size a lot. Today, I'd say we should implement it again since the build tools and stuff have advanced.
